# Generated by Django 5.0 on 2023-12-20 08:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cartorder_price_alter_cartorderitems_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(default='category.jpg', upload_to='category', validators=[core.models.validate_file_extension]),
        ),
    ]
