# Generated by Django 5.0 on 2023-12-20 08:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='svg',
            field=models.FileField(default='category.jpg', upload_to='category', validators=[core.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='category.jpg', upload_to='category'),
        ),
    ]
