# Generated by Django 5.0 on 2023-12-21 07:15

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_vendor_date_alter_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='user.jpg', upload_to=core.models.user_directory_path),
        ),
    ]
